name: Build and Deploy BB Register

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build register
        run: |
          docker run --rm --workdir /workspace -v "${{ github.workspace }}:/workspace" \
            ghcr.io/opengeospatial/bblocks-postprocess --clean true --base-url ${{ steps.baseurl.outputs.url || 'https://example.org' }}/register/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build-local/generateddocs
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
